config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'information#index'
  get 'about' => 'information#about'
  get 'faq'   => 'information#faq'
  get 'benefits' => 'information#benefits'
  get 'tos' => 'information#tos'
  get 'privacy' => 'information#privacy'

  root 'information#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end

  def benefits
  end

  def tos
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/about.html.erb
<h1>Information#about</h1>
<p>Find me in app/views/information/about.html.erb</p>

app/views/information/benefits.html.erb
<h1>Information#benefits</h1>
<p>Find me in app/views/information/benefits.html.erb</p>

app/views/information/faq.html.erb
<h1>Information#faq</h1>
<p>Find me in app/views/information/faq.html.erb</p>

app/views/information/index.html.erb
<h1>Information#index</h1>
<p>Find me in app/views/information/index.html.erb</p>

app/views/information/privacy.html.erb
<h1>Information#privacy</h1>
<p>Find me in app/views/information/privacy.html.erb</p>

app/views/information/tos.html.erb
<h1>Information#tos</h1>
<p>Find me in app/views/information/tos.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doctoraso</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>Menu
<ul>
  <li><%= link_to "Find",   index_path %></li>
  <li><%= link_to "about",   about_path %></li>
  <li><%= link_to "faq",   faq_path %></li>
  <li><%= link_to "benefits",   benefits_path %></li>
  <li><%= link_to "tos",   tos_path %></li>
  <li><%= link_to "privacy",   privacy_path %></li>
</ul>
</div>


<%= yield %>

</body>
</html>